# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_packages:
  - EMCluster
  - Rcpp
  - covr
  - pkgdown
sudo: false
cache: packages
warnings_are_errors: true
notifications:
  email:
    - gzthompson@gmail.com
after_success:
  - Rscript -e 'covr::codecov()'
os:
 - linux
 - osx
r:
 - devel
 - release
 - oldrel
matrix:
  exclude:
  - r: devel
    os: osx
  - r: oldrel
    os: osx
before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); covr::codecov();'
git:
   depth: 9999999
