# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r_packages:
  - EMCluster
  - Rcpp
  - covr
sudo: false
cache: packages
warnings_are_errors: true
r:
  - release
  - devel
notifications:
  email:
    - gzthompson@gmail.com

after_success:
  - Rscript -e 'covr::codecov()'