// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_gini
double c_gini(NumericVector x);
RcppExport SEXP _catsim_c_gini(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c_gini(x));
    return rcpp_result_gen;
END_RCPP
}
// c_ginicorr
double c_ginicorr(NumericVector x, double k);
RcppExport SEXP _catsim_c_ginicorr(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(c_ginicorr(x, k));
    return rcpp_result_gen;
END_RCPP
}
// c_cfunc
double c_cfunc(NumericVector x, NumericVector y, double c, double k, bool sqrtflag);
RcppExport SEXP _catsim_c_cfunc(SEXP xSEXP, SEXP ySEXP, SEXP cSEXP, SEXP kSEXP, SEXP sqrtflagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type sqrtflag(sqrtflagSEXP);
    rcpp_result_gen = Rcpp::wrap(c_cfunc(x, y, c, k, sqrtflag));
    return rcpp_result_gen;
END_RCPP
}
// c_meansfunc
double c_meansfunc(NumericVector x, NumericVector y, double c);
RcppExport SEXP _catsim_c_meansfunc(SEXP xSEXP, SEXP ySEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(c_meansfunc(x, y, c));
    return rcpp_result_gen;
END_RCPP
}
// c_cohen
double c_cohen(NumericVector x, NumericVector y);
RcppExport SEXP _catsim_c_cohen(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_cohen(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_adj_rand
double c_adj_rand(NumericVector x, NumericVector y);
RcppExport SEXP _catsim_c_adj_rand(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_adj_rand(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_rand
double c_rand(NumericVector x, NumericVector y);
RcppExport SEXP _catsim_c_rand(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_rand(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_nmi
double c_nmi(NumericVector x, NumericVector y);
RcppExport SEXP _catsim_c_nmi(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_nmi(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_ami
double c_ami(NumericVector x, NumericVector y);
RcppExport SEXP _catsim_c_ami(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_ami(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_jaccard
double c_jaccard(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _catsim_c_jaccard(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_jaccard(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_dice
double c_dice(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _catsim_c_dice(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_dice(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_hamming
double c_hamming(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _catsim_c_hamming(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_hamming(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_catssim_2d
Rcpp::NumericVector c_catssim_2d(Rcpp::NumericMatrix x, Rcpp::NumericMatrix y, Rcpp::IntegerVector window, std::string method, double c1, double c2, bool sqrtgini);
RcppExport SEXP _catsim_c_catssim_2d(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP methodSEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP sqrtginiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type window(windowSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< bool >::type sqrtgini(sqrtginiSEXP);
    rcpp_result_gen = Rcpp::wrap(c_catssim_2d(x, y, window, method, c1, c2, sqrtgini));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_catsim_c_gini", (DL_FUNC) &_catsim_c_gini, 1},
    {"_catsim_c_ginicorr", (DL_FUNC) &_catsim_c_ginicorr, 2},
    {"_catsim_c_cfunc", (DL_FUNC) &_catsim_c_cfunc, 5},
    {"_catsim_c_meansfunc", (DL_FUNC) &_catsim_c_meansfunc, 3},
    {"_catsim_c_cohen", (DL_FUNC) &_catsim_c_cohen, 2},
    {"_catsim_c_adj_rand", (DL_FUNC) &_catsim_c_adj_rand, 2},
    {"_catsim_c_rand", (DL_FUNC) &_catsim_c_rand, 2},
    {"_catsim_c_nmi", (DL_FUNC) &_catsim_c_nmi, 2},
    {"_catsim_c_ami", (DL_FUNC) &_catsim_c_ami, 2},
    {"_catsim_c_jaccard", (DL_FUNC) &_catsim_c_jaccard, 2},
    {"_catsim_c_dice", (DL_FUNC) &_catsim_c_dice, 2},
    {"_catsim_c_hamming", (DL_FUNC) &_catsim_c_hamming, 2},
    {"_catsim_c_catssim_2d", (DL_FUNC) &_catsim_c_catssim_2d, 7},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_catsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
