# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_gini <- function(x) {
    .Call(`_catsim_C_gini`, x)
}

C_ginicorr <- function(x, k) {
    .Call(`_catsim_C_ginicorr`, x, k)
}

C_cfunc <- function(x, y, c, k) {
    .Call(`_catsim_C_cfunc`, x, y, c, k)
}

C_meansfunc <- function(x, y, c) {
    .Call(`_catsim_C_meansfunc`, x, y, c)
}

