# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_gini <- function(x) {
    .Call(`_catsim_c_gini`, x)
}

c_ginicorr <- function(x, k) {
    .Call(`_catsim_c_ginicorr`, x, k)
}

c_cfunc <- function(x, y, c, k, sqrtflag) {
    .Call(`_catsim_c_cfunc`, x, y, c, k, sqrtflag)
}

c_meansfunc <- function(x, y, c) {
    .Call(`_catsim_c_meansfunc`, x, y, c)
}

c_cohen <- function(x, y) {
    .Call(`_catsim_c_cohen`, x, y)
}

c_adj_rand <- function(x, y) {
    .Call(`_catsim_c_adj_rand`, x, y)
}

c_rand <- function(x, y) {
    .Call(`_catsim_c_rand`, x, y)
}

c_nmi <- function(x, y) {
    .Call(`_catsim_c_nmi`, x, y)
}

c_ami <- function(x, y) {
    .Call(`_catsim_c_ami`, x, y)
}

