# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_gini <- function(x) {
    .Call(`_catsim_C_gini`, x)
}

C_ginicorr <- function(x, k) {
    .Call(`_catsim_C_ginicorr`, x, k)
}

C_cfunc <- function(x, y, c, k, sqrtflag) {
    .Call(`_catsim_C_cfunc`, x, y, c, k, sqrtflag)
}

C_meansfunc <- function(x, y, c) {
    .Call(`_catsim_C_meansfunc`, x, y, c)
}

C_Cohen <- function(x, y) {
    .Call(`_catsim_C_Cohen`, x, y)
}

C_AdjRand <- function(x, y) {
    .Call(`_catsim_C_AdjRand`, x, y)
}

C_Rand <- function(x, y) {
    .Call(`_catsim_C_Rand`, x, y)
}

C_NMI <- function(x, y) {
    .Call(`_catsim_C_NMI`, x, y)
}

